{
 "title": "BkkDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(up{namespace=\"default\", service=~\"backend-service|frontend-service\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{namespace=\"default\", status=~\"404|500\"}) / sum(flask_http_request_total{namespace=\"default\", status=~\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"backend|frontend\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx 5xx frontend and backend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "flask_http_request_total{container=~\"frontend|backend\", status=~\"404|500\", namespace=\"default\", endpoint=~\"backend|frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_max_usage_bytes{container=~\"backend|frontend\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tracing ALL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "service": "backend" }
   ]
  }
 ]
}